# Generated by Django 3.2.4 on 2021-06-17 07:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripemodel',
            name='card_number',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{0,9}$')]),
        ),
        migrations.AddField(
            model_name='stripemodel',
            name='cvc',
            field=models.CharField(blank=True, max_length=3, null=True, validators=[django.core.validators.RegexValidator('^\\d{0,9}$')]),
        ),
        migrations.AddField(
            model_name='stripemodel',
            name='exp_month',
            field=models.CharField(blank=True, max_length=2, null=True, validators=[django.core.validators.RegexValidator('^\\d{0,9}$')]),
        ),
        migrations.AddField(
            model_name='stripemodel',
            name='exp_year',
            field=models.CharField(blank=True, max_length=4, null=True, validators=[django.core.validators.RegexValidator('^\\d{0,9}$')]),
        ),
        migrations.AlterField(
            model_name='stripemodel',
            name='card_id',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stripemodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stripemodel', to=settings.AUTH_USER_MODEL),
        ),
    ]
