# Generated by Django 3.2.4 on 2021-06-17 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210617_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripemodel',
            name='card_number',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
    ]
