# Generated by Django 3.2.4 on 2021-06-20 06:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_rename_stripe_email_stripemodel_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripemodel',
            name='address_city',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='stripemodel',
            name='address_country',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='stripemodel',
            name='address_state',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='stripemodel',
            name='address_zip',
            field=models.CharField(blank=True, max_length=6, null=True, validators=[django.core.validators.RegexValidator('^\\d{0,9}$')]),
        ),
        migrations.AddField(
            model_name='stripemodel',
            name='name_on_card',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
