# Generated by Django 3.2.4 on 2021-06-24 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0010_billingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billingmodel', to=settings.AUTH_USER_MODEL),
        ),
    ]
