# Generated by Django 3.2.4 on 2021-06-26 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_ordermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
