# Generated by Django 3.2.4 on 2021-06-26 15:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_auto_20210626_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='pin_code',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^\\d{0,9}$')]),
        ),
        migrations.AlterField(
            model_name='stripemodel',
            name='address_zip',
            field=models.CharField(blank=True, max_length=6, null=True, validators=[django.core.validators.RegexValidator('^\\d{0,9}$')]),
        ),
    ]
