# Generated by Django 3.2.4 on 2021-06-29 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_alter_ordermodel_paid_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='paid_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
