# Generated by Django 3.2.4 on 2021-06-29 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_alter_ordermodel_paid_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stripemodel',
            name='cvc',
        ),
    ]
