# Generated by Django 3.2.4 on 2021-06-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_remove_stripemodel_cvc'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='ordered_item',
            field=models.CharField(blank=True, default='Not Set', max_length=200, null=True),
        ),
    ]
