# Generated by Django 3.2.4 on 2021-06-30 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_ordermodel_ordered_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
