# Generated by Django 3.2.4 on 2021-06-15 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
    ]
