# Generated by Django 3.2.4 on 2021-06-28 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='no_preview_image.png', null=True, upload_to=''),
        ),
    ]
